### ISSUE TITLE
prerender.py Error

### ISSUE THREAD

**Issue by SwagJ** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#2]
Hi @stepankonev,

Thank you for sharing your implementation. When I tried to prerender data for test set. There's been an error about void map info. Actually the latest Waymo Motion Dataset has few data samples that are missing map roadinfo for test set. I am just wondering how did you handled this issue? Thank you in advance. 

Best,

**Comment by stepankonev** [comment]
Hi!
You can try to provide some average predictions for those cases, or predictions with all zeroes. mAP and SoftmAP metrics are robust to outliers and these few cases will not affect the score too much

**Comment by SwagJ** [comment]
Hi @stepankonev,

Thank you for your swift reply. I will try your suggestion. Actually, I do have two extra question. 
1. The loss is decreasing very fast at early iteration and dropped to negative at around 300th iteration. Is this normal?
2. In your technical report, you used NMS for post-processing process. However, for single decoder, the output trajectory is already 6. So, is the NMS process only applied on multi decoder case? 
I am looking forward to your reply. Thank you in advance. 

Best,
