### ISSUE TITLE
AV relative features.

### ISSUE THREAD

**Issue by smartbarbarian** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#22]
Hi Stepan,

You did a great job and your code is so elegant. 
And I have several questions about multipath++. The paper said it will did
MCG(φ(interaction)1:n, [φ(state), φ(interaction) AV ]) 
But it seems there is only MCG(φ(interaction)1:n, φ(state)). Do I misunderstand it?
Could you help me to clarify it? Thank you so much!

Best Regards,

**Comment by stepankonev** [comment]
Hi @smartbarbarian , thank you for your attention!
In this code (in contrast to the MultiPath++ paper) the AV is not modeled separately.
Best,
