### ISSUE TITLE
About prerendering testing data

### ISSUE THREAD

**Issue by arya-snh** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#26]
The prerender/prerender.py script doesnt seem to work on the testing tfrecords in Waymo motion dataset. An error occurs in the prerender/utils/vectorizer.py script. Please help.
PFA error:

![Screenshot from 2022-12-21 11-30-15](https://user-images.githubusercontent.com/114855347/208832705-57244822-1ab1-4e46-9c65-8d6db1f30ebd.png)

**Comment by xijun-cs** [comment]
Hi @arya-snh, How did you solve this issue?

**Comment by stepankonev** [comment]
As far as I remember, some records in the dataset have missing roadgraphs, thus it fails here. You might want to use another version of the dataset or allow for empty roadgraph.

**Comment by xijun-cs** [comment]
Thanks a lot. I will skip those data points.
