### ISSUE TITLE
Request for additional performance metrics

### ISSUE THREAD

**Issue by jxmmy7777** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#27]
Hello  @stepankonev ,
Thank you for sharing your code on Github. I have been reviewing the technical report and have noticed that only the mAP on the test results is reported. I was wondering if it would be possible for you to share other performance metrics such as minADE, minFDE, etc. Additionally, I was wondering if the performance of the model seems to be consistent with the validation set/test set.

Thank you for your time and assistance. I look forward to hearing from you.

Best regards,

**Comment by stepankonev** [comment]
Hello @jxmmy7777 ,
Thank you for your attention to the repository. Test results can be found at the official competition website under MPA name and currently are the following:

| **Object Type** | **Measurement Time (s)** | **Soft mAP** | **mAP** | **Min ADE** | **Min FDE** | **Miss Rate** | **Overlap Rate** |
|-----------------|--------------------------|--------------|---------|-------------|-------------|---------------|------------------|
| Vehicle         | 3                        | 0.5656       | 0.5497  | 0.2914      | 0.5332      | 0.0931        | 0.0226           |
| Vehicle         | 5                        | 0.4469       | 0.4408  | 0.6099      | 1.2239      | 0.1429        | 0.0491           |
| Vehicle         | 8                        | 0.3276       | 0.3242  | 1.2022      | 2.7640      | 0.2256        | 0.1064           |
| Vehicle         | Avg                      | 0.4467       | 0.4382  | 0.7012      | 1.5070      | 0.1539        | 0.0594           |
| Pedestrian      | 3                        | 0.4704       | 0.4606  | 0.1697      | 0.3122      | 0.0716        | 0.2405           |
| Pedestrian      | 5                        | 0.3708       | 0.3646  | 0.3246      | 0.6584      | 0.1040        | 0.2641           |
| Pedestrian      | 8                        | 0.3081       | 0.3023  | 0.5771      | 1.2843      | 0.1359        | 0.2948           |
| Pedestrian      | Avg                      | 0.3831       | 0.3758  | 0.3572      | 0.7516      | 0.1038        | 0.2665           |
| Cyclist         | 3                        | 0.4265       | 0.4216  | 0.3370      | 0.6292      | 0.1919        | 0.0460           |
| Cyclist         | 5                        | 0.3629       | 0.3596  | 0.6459      | 1.2922      | 0.2135        | 0.0880           |
| Cyclist         | 8                        | 0.2585       | 0.2563  | 1.1636      | 2.5588      | 0.2640        | 0.1401           |
| Cyclist         | Avg                      | 0.3493       | 0.3458  | 0.7155      | 1.4934      | 0.2231        | 0.0914           |
| Avg             | 3                        | 0.4875       | 0.4773  | 0.2660      | 0.4915      | 0.1189        | 0.1030           |
| Avg             | 5                        | 0.3935       | 0.3883  | 0.5268      | 1.0582      | 0.1534        | 0.1338           |
| Avg             | 8                        | 0.2981       | 0.2943  | 0.9810      | 2.2024      | 0.2085        | 0.1804           |
| Avg             | Avg                      | 0.3930       | 0.3866  | 0.5913      | 1.2507      | 0.1603        | 0.1391           |

No significant divergence between test and val metrics was observed if using same dataset version
