### ISSUE TITLE
multi-GPU version

### ISSUE THREAD

**Issue by MichaelYu781** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#5]
hi, @stepankonev !
Current code is with single gpu and the training speed is relatively slow (about 1.5 iteration per second from our side). 
Do you have multi-GPU version?

**Comment by stepankonev** [comment]
Hi, @MichaelYu781 !
I was training the model on the single GPU so the multi-GPU version is not provided.
Best,

**Comment by MichaelYu781** [comment]
Got it. Thank you, sir!

**Comment by MichaelYu781** [comment]
Hi, @stepankonev !
What will the loss value finally converges to? In case the loss value is always positive,  it will converges to zero. But when i train this model, the loss is negative. Although it gets down, but i don't know to which value it means the model is trained almost completely. The attached photo is my training log, is this normal?
Thanks for your time!
<img width="315" alt="Snipaste_2022-07-18_23-22-30" src="https://user-images.githubusercontent.com/78360527/179546918-14280e0a-f476-408f-8051-852f5ce129aa.png">

**Comment by stepankonev** [comment]
Hello! Please, let's keep the discussion clean. This issue should be devoted to the multi-gpu version of the model. It would also be great if you share the config in the other issue, previously checking for duplicates. Thanks!
PS I believe now it should have converged to some point
