### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by XZloveWYB** [stepankonev/waymo-motion-prediction-challenge-2022-multipath-plus-plus#6]
Hello! @stepankonev Thank you very much for sharing this great code!

I want to know the evaluation metrics of my local computer running the code you shared. Could you please share the submit file uploaded to Waymo Motion Prediction Challenge? Looking forward to your reply!

**Comment by stepankonev** [comment]
Dear @XZloveWYB, thank you for your attention to the repo! Unfortunately, I am not sure that sharing the submission file meets the rules.
Best,

**Comment by XZloveWYB** [comment]
Ok, I see, thank you for your reply!
